import { NgModule } from "@angular/core";
import {
    FormBlocksPipe,
    FormBlockValuePipe,
    FormInstanceBlockPipe,
    FormInstanceBlocks,
    FormInstanceCreationPipe,
    FormInstanceModificationPipe,
    FormInstanceTitlePipe,
    FormInstanceTypePipe,
    FormInstanceValuePipe,
    FormsAuthorPipe,
    FormsChangeFieldPipe, FormsGetInstance,
    FormsGetInstanceNode,
    FormsGetReferenceName, FormsValueForKeyPipe,
    FormsWithIdPipe, FormTitlePipe, FormWrapperBuildPipe,
    FormWrapperChangeFieldPipe,
} from "./forms.pipe";

@NgModule({
    declarations: [
        FormsValueForKeyPipe,
        FormsWithIdPipe,
        FormsGetInstance,
        FormsGetInstanceNode,
        FormsGetReferenceName,
        FormsChangeFieldPipe,
        FormTitlePipe,
        FormsAuthorPipe,
        FormInstanceTitlePipe,
        FormInstanceCreationPipe,
        FormInstanceModificationPipe,
        FormBlocksPipe,
        FormInstanceBlocks,
        FormBlockValuePipe,
        FormInstanceTypePipe,
        FormInstanceBlockPipe,
        FormInstanceValuePipe,
        FormWrapperBuildPipe,
        FormWrapperChangeFieldPipe,
    ],
    exports: [
        FormsValueForKeyPipe,
        FormsWithIdPipe,
        FormsGetInstance,
        FormsGetInstanceNode,
        FormsGetReferenceName,
        FormsChangeFieldPipe,
        FormTitlePipe,
        FormsAuthorPipe,
        FormInstanceTitlePipe,
        FormInstanceCreationPipe,
        FormInstanceModificationPipe,
        FormBlocksPipe,
        FormInstanceBlocks,
        FormBlockValuePipe,
        FormInstanceTypePipe,
        FormInstanceBlockPipe,
        FormInstanceValuePipe,
        FormWrapperBuildPipe,
        FormWrapperChangeFieldPipe,
    ]
})
export class CeFormsPipesModule {}